### PR TITLE
version bump to 2.1.4

### PR DESCRIPTION
**Pull request by wseaton**
updating this to support celery 4.*, more PRs are coming for kombu and then celery

### CODE REVIEW

**Comment by wseaton** [comment]
any love @anguslees or @kwilcox? sorry, fat fingered the close PR button.

**Comment by kwilcox** [comment]
We might want to create 1.x branch to support patches for that release. Do you know of the support plan for 1.x?

**Comment by wseaton** [comment]
I'm unsure of the longer term support plan for 1.x, but have no problem creating a 1.x branch to support bug fixes.

**Comment by wseaton** [comment]
@kwilcox I'm not a maintainer of this feedstock so I don't have write access to create a 1.x branch, if this is changed I can take care of it.

**Comment by kwilcox** [comment]
Make a PR adding yourself to the maintainers list in the recipe and it
should take care of itself (I'll accept the PR)!

**Pull request closed without merging**
